# Generated by Django 4.0.1 on 2022-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_alter_quiz_name_alter_quiz_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='creationTime',
            field=models.DateTimeField(null=True),
        ),
    ]
