# Generated by Django 4.0.1 on 2022-03-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_quiz_islocked_score_creationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizTime',
            field=models.TimeField(null=True),
        ),
    ]
