# Generated by Django 4.0.1 on 2022-03-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('profilePic', models.ImageField(upload_to='images/users/')),
                ('institution', models.CharField(max_length=50)),
                ('dob', models.DateField(default='')),
                ('isNewsletterSubscribed', models.BooleanField(default=True)),
                ('totalQuizzesOrganized', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('profilePic', models.ImageField(upload_to='images/users/')),
                ('institution', models.CharField(max_length=50)),
                ('dob', models.DateField(default='')),
                ('isNewsletterSubscribed', models.BooleanField(default=True)),
                ('rating', models.IntegerField(default=0)),
                ('totalQuizzesGiven', models.IntegerField(default=0)),
                ('totalCorrectAnswers', models.IntegerField(default=0)),
                ('totalWrongAnswers', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
    ]
