# Generated by Django 4.0.1 on 2022-03-11 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=255)),
                ('statement', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discussions.doubt')),
                ('trusted_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discussions.doubt')),
            ],
        ),
    ]
