# Generated by Django 4.0.1 on 2022-03-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussions', '0007_alter_reply_creator_alter_reply_trusted_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='trusted_creator',
            new_name='trustedCreator',
        ),
    ]
